# Database
POSTGRESQL_USERNAME: user
POSTGRESQL_PASSWORD: pleaseletmein
POSTGRESQL_HOST: 192.168.1.179
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: docdatabase

# Server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: prod

# Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID:
EMAIL_PASSWORD:
VERIFY_EMAIL_HOST: http://localhost:5173

JWT_EXPIRATION: 432_000_000
JWT_SECRET: ${SECRET}